version: '3'

services:
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins-for-java-odf-edit-sample
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
