version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/postgres:11-alpine-ram
        environment:
          TERM: dumb
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: データベースの初期化
          command: |
            sudo apt-get install postgresql-client-9
            psql -d postgresql://root@localhost/circle_test -f ./env/local/postgres/init_sql/01_createdb.sql
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: テスト
          command: ./gradlew test jacocoTestReport
      - store_test_results:
          path: ./build/test-results
      - store_artifacts:
          path: ./build/reports
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
  static_analyze:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          TERM: dumb
          TZ: Asia/Tokyo
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: SonarScanerを実行、結果をSonarCloudに送る
          command: |
            ./gradlew sonarqube -Dsonar.organization=kazuhito-m-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONARCLOUD_KEY} -x test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - static_analyze:
          requires:
            - build
          filters:
            branches:
              only: master
