version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          TERM: dumb
          TZ: Asia/Tokyo
      - image: circleci/postgres:12-beta1-alpine-ram
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: データベースの初期化
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            sudo apt-get update
            sudo apt-get install postgresql-client-9.6
            psql -d postgresql://postgres@localhost/circle_test -f ./env/local/postgres/init_sql/01_createdb.sql
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: テスト
          command: ./gradlew test jacocoTestReport
      - store_test_results:
          path: ./build/test-results
      - store_artifacts:
          path: ./build/reports
      - persist_to_workspace:
          root: ./
          paths:
            - .git
            - build
            - build.gradle
            - gradle
            - gradlew
            - setting.gradle
            - src
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
  static_analyze:
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          TERM: dumb
          TZ: Asia/Tokyo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - deploy:
          name: SonarScanerを実行、結果をSonarCloudに送る
          command: |
            ./gradlew sonarqube \
              -Dsonar.organization=kazuhito-m \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONARCLOUD_KEY \
              -Dsonar.projectKey=java-odf-edit-sample \
              -Dsonar.java.binaries=./build/classes/java/main \
              --debug \
              -x test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - static_analyze:
          requires:
            - build
          filters:
            branches:
              only: master
