version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.1
        environment:
          TERM: dumb
          TZ: Asia/Tokyo
      - image: cimg/postgres:15.0
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: データベースの初期化
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            sudo apt-get update
            sudo apt-get install postgresql-client
            psql -d postgresql://postgres@localhost/circle_test -f ./env/local/postgres/init_sql/01_createdb.sql
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: テスト
          command: ./gradlew test jacocoTestReport
      - store_test_results:
          path: ./build/test-results
      - store_artifacts:
          path: ./build/reports
      - persist_to_workspace:
          root: ./
          paths:
            - .git
            - build
            - build.gradle
            - gradle
            - gradlew
            - settings.gradle
            - src
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - discord/status:
          fail_only: true
          failure_message: "Triggered User: **${CIRCLE_USERNAME}**\\nBranch: **${CIRCLE_BRANCH}**\\n\\nCircleCI テストに失敗しました。 JOB: **$CIRCLE_JOB**"
          webhook: "${DISCORD_WEBHOOK}"

  static_analyze:
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          TERM: dumb
          TZ: Asia/Tokyo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - deploy:
          name: SonarScanerを実行、結果をSonarCloudに送る
          command: |
            ./gradlew sonarqube \
              -Dsonar.organization=kazuhito-m \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONARCLOUD_KEY} \
              -x test
      - discord/status:
          fail_only: true
          failure_message: "Triggered User: **${CIRCLE_USERNAME}**\\nBranch: **${CIRCLE_BRANCH}**\\n\\nCircleCI 静的解析に失敗しました。 JOB: **$CIRCLE_JOB**"
          webhook: "${DISCORD_WEBHOOK}"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: kazuhito_m-products
      - static_analyze:
          requires:
            - build
          filters:
            branches:
              only: master
          context: kazuhito_m-products
