name: ci

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 19 ]
        postgres: [ 15.0 ]

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}-alpine
        env:
          POSTGRES_PASSWORD: postgres
          LANG: ja_JP.UTF-8
          LANGUAGE: ja_JP.UTF-8
          LC_ALL: ja_JP.UTF-8
          TZ: Asia/Tokyo
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize Postgres Database
        run: psql -f ${{ github.workspace }}/env/local/postgres/init_sql/01_createdb.sql postgresql://postgres:postgres@localhost:5432/postgres

      - name: Setup JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk }}

      - name: Cache gradle
        uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew clean test

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: CI結果 - Java ODF Edit Sample
          fields: repo,message,commit,author,action,eventName,workflow,pullRequest
          if_mention: failure
          mention: 'U0HKET970'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

      - name: Notify Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            {{ EVENT_PAYLOAD.repository.full_name }} のテストが失敗しました。
            
            User: Test
            二行改行とかできんの？
